cache: bundler
sudo: false
language: ruby
services:
  - redis-server

matrix:
  include:
    - rvm: 2.3.8
      env: "CHECK=rubocop"

    - rvm: 2.3.8
      env: "CHECK=test"

    - rvm: 2.4.5
      env: "CHECK=test"

    - rvm: 2.5.3
      env: "CHECK=test"

    - rvm: jruby-9.1.17.0
      env: "CHECK=test"

    - rvm: jruby-9.2.5.0
      env: "CHECK=test"

  # Remove the allow_failures section once
  # Rubocop is required for Travis to pass a build
  allow_failures:
    - rvm: 2.3.8
      env: "CHECK=rubocop"

install:
  - gem update --system
  - gem install bundler
  - bundle --version
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
script:
  - "bundle exec rake $CHECK"
