# For local development run with a dummy provider
version: '3.2'
services:
  vmpooler:
    build:
      context: ../
      dockerfile: docker/Dockerfile_local
    volumes:
      - type: bind
        source: ${PWD}/vmpooler.yaml
        target: /etc/vmpooler/vmpooler.yaml
      - type: bind
        source: ${PWD}/providers.yaml
        target: /etc/vmpooler/providers.yaml
    ports:
      - "4567:4567"
    networks:
      - redis-net
    environment:
      - VMPOOLER_DEBUG=true # for use of dummy auth
      - VMPOOLER_CONFIG_FILE=/etc/vmpooler/vmpooler.yaml
      - REDIS_SERVER=redislocal
      - EXTRA_CONFIG=/etc/vmpooler/providers.yaml
      - LOGFILE=/dev/stdout
      - LDAP_PORT=636
    image: vmpooler-local
    depends_on:
      - redislocal
  redislocal:
    image: redis
    # Uncomment this if you don't want the redis data to persist
    #command: "redis-server --save '' --appendonly no"
    ports:
      - "6379:6379"
    networks:
      - redis-net

networks:
  redis-net:
